---
# https://docs.aws.amazon.com/secretsmanager/latest/userguide/integrating_csi_driver_SecretProviderClass.html
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: ${namespace}
  name: ascp-test-pod-identity-secrets-1
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"  # Pod Identityを使用する場合はtrue
    objects: |
        - objectName: "${secrets_name}"
          objectType: "secretsmanager"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${namespace}
  name: ascp-test-pod-identity-deployment-1
spec:
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      serviceAccountName: ${service_account}
      containers:
      - name: ascp-test-pod-identity-1
        image: ubuntu
        command: ["sleep", "infinity"]
        # SecretsManagerをコンテナにマウント
        volumeMounts:
        - name: secrets-store  # volumes[].name
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      # CSIストレージ指定
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "ascp-test-pod-identity-secrets-1"  # SecretProviderClass で定義した metadata.name