---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvidia-smi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvidia-smi
  template:
    metadata:
      labels:
        app: nvidia-smi
    spec:
      containers:
        - name: nvidia-smi
          # https://hub.docker.com/r/nvidia/cuda/tags
          image: nvidia/cuda:12.6.0-cudnn-devel-ubuntu22.04
          args:
          - "nvidia-smi"
          resources:
            limits:
              nvidia.com/gpu: 1
      affinity:
        # Node Affinityの例: https://cstoku.dev/posts/2018/k8sdojo-18/#node-affinity%E3%81%AE%E4%BE%8B
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "karpenter.sh/nodepool"
                    operator: "In"
                    values:
                      - "bottlerocket-x86-64-nvidia-standard"
      #tolerations:
      #  - key: "nvidia.com/gpu"
      #    operator: "Exists"
      #    effect: "NoSchedule"