apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflate-gpu
  template:
    metadata:
      labels:
        app: inflate-gpu
    spec:
      containers:
        - name: inflate-gpu
          # https://catalog.ngc.nvidia.com/orgs/nvidia/teams/k8s/containers/cuda-sample/tags
          image: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda12.5.0-ubuntu22.04"
          resources:
            limits:
              nvidia.com/gpu: 1
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
