# 設定値: https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/values.yaml
opencost:
  customPricing:
    enabled: true
    provider: aws
    costModel:
      # デフォルト値:https://github.com/opencost/opencost/blob/develop/configs/default.json
      # https://github.com/opencost/opencost/blob/develop/configs/aws.json
      description: Modified pricing configuration.
      CPU: 0.031611
      spotCPU: 0.006655
      RAM: 0.004237
      spotRAM: 0.000892
      GPU: 0.95
      storage: 0.00005479452
      zoneNetworkEgress: 0.01
      regionNetworkEgress: 0.01
      internetNetworkEgress: 0.143
      spotLabel: ""
      spotLabelValue: ""
      awsServiceKeyName: ""
      awsServiceKeySecret: ""
      awsSpotDataRegion: "ap-southeast-1"
      awsSpotDataBucket: "${datafeed_bucket_name}"
      awsSpotDataPrefix: ""
      athenaBucketName: ""
      athenaRegion: ""
      athenaDatabase: ""
      athenaTable: ""
      projectID: "${account_id}"
  exporter:
    defaultClusterId: ${cluster_name}
    extraEnv:
      EMIT_KSM_V1_METRICS: "false"
      EMIT_KSM_V1_METRICS_ONLY: "true"
      LOG_LEVEL: debug # debug, info, warn, error
  prometheus:
    internal:
      enabled: true
      serviceName: prometheus-server
      namespaceName: prometheus-system
  ui:
    enabled: true
  metrics:
    serviceMonitor:
      enabled: true
      namespace: prometheus-system
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: ${servicea_account_role_arn}